### PR TITLE
Move from npm to yarn

### PR DESCRIPTION
**Pull request by sadafie**
I accidentally already added a `yarn.lock` file with my Greenkeeper Monday tasks yesterday, but this completes the task. It also adds the eslint precommit hook at @eilinora 's request.

### CODE REVIEW

**Comment by eilinora** [comment]
@sadafie does this add the pre-commit check for eslint? :crossed_fingers: doesn't look like it

**Comment by sadafie** [comment]
> does this add the pre-commit check for eslint? 

Yep, the following in `package.json` should do the trick. Let me know if it doesn't work for you.

```
"precommit": "git status --porcelain | awk 'match($1, \"[ACM]\"){print $2}' | grep '[js|jsx]$' | xargs eslint",
```

**Comment by mattkime** [comment]
@sadaf the precommit hook needs `husky` added as a dependency.

**Comment by eilinora** [comment]
shwoo not crazy! i had tried adding the precommit in package but was missing the `husky` requirement

**Comment by sadafie** [comment]
ah okay, we can file a follow up ticket

**Pull request merged**
