### PR TITLE
Remove unused packages, update peerDependencies, upgrade some packages -

### PR DESCRIPTION
**Pull request by mmcgahan**
Recreation of #691 without the migration branch code @sadafie

> I noticed that the package.json for MWC hasn't gotten attention in some time. I upgraded package versions, removed unused dependencies, and so forth. Certain peerDependencies introduce unnecessary dependencies for pro-web. Overall, a bit of cleanup. Storybook runs correct and I just need to use the beta version of this PR to test in mup-web and pro-web.

### CODE REVIEW

**Comment by mmcgahan** [comment]
LGTM

**Comment by sadafie** [comment]
Cool, I'm going to test the beta branch in mup-web and pro-web and if all is good, will merge this. Thanks for helping update the PR @mmcgahan !

**Comment by mmcgahan** [comment]
@sadafie just wanted to make sure this didn't get left behind

**Comment by sadafie** [comment]
Tested in mup-web and everything is good.

**Pull request merged**
